FROM --platform=$BUILDPLATFORM golang:1.26-alpine AS builder

WORKDIR /app

# Install dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy source code
COPY . .

ARG TARGETARCH
# Build the application
RUN CGO_ENABLED=0 GOOS=linux GOARCH=$TARGETARCH go build -o search-gateway ./cmd/server/main.go

# Use a scratch image for smallest possible size
FROM alpine:latest

WORKDIR /app

RUN apk --no-cache add ca-certificates tzdata

COPY --from=builder /app/search-gateway .

ENV PORT=8080

EXPOSE 8080

CMD ["./search-gateway"]
